# syntax=docker/dockerfile:1.3-labs
FROM       ubuntu:latest
RUN        mkdir -p /root/torrent
RUN        mkdir -p /root/script
RUN        mkdir -p /root/log
RUN        apt-get update
RUN        apt-get upgrade -y
RUN        apt-get install software-properties-common -y
RUN        add-apt-repository universe -y
RUN        apt-get update
RUN        apt-get install python3-pip python3.10 -y
RUN        pip3 install requests
RUN        pip install schedule
WORKDIR /root/script
COPY archiver.py archiver.py
CMD ["python3", "archiver.py"]


